ipfs/distributions

build-go.sh, site/public/_js/_platform.js, site/public/index.jade, tasks/dist.js
This fixes the package names, but is still missing the switch to `.tar.gz` for some oses.
Ref #33
=> fix(build): Change package name to match the constraints

build-go.sh
This lets you know that your daemon is not on.
=> Add a fail error if daemon not running

site/config.toml
This prevents hugo from generating the tags/categories directories.
=> remove taxonomies

dists/go-ipfs/build_matrix, dists/go-ipfs/mkdist.js, dists/gx-go/build_matrix, dists/gx/build_matrix
go-ipfs actually "supports" (it builds, at least) arm64. However, we don't currently build it.
Is this the correct way to add support?
=> add arm64 support

build-go.sh, deps-check.sh
This PR aims to close https://github.com/ipfs/distributions/issues/152 by exposing CID and additionally generating a plain SHA512 hash for every artifact of new releases.
I had a short chat with someone (sorry, forgot the name :() about things that we could improve as an open source project to make it easier to package our software.
Number one issue was that we do not publish checksums and package managers can't verify downloads without additional orchestration. This makes package maintainer's work harder than it should be.
I mentioned all our artifacts are content-addressed and it is possible to get CID for every file but there is a good argument about learning curve of IPFS concepts and multihash/cids not being supported by default userland tools in unix-like systems (yet), while things …
=> Publish checksums for every artifact

README.md
Checksum files were added in https://github.com/ipfs/distributions/pull/199 and are present in the latest releases such as [go-ipfs v0.4.18](https://dist.ipfs.io/go-ipfs/v0.4.18).
cc @dignifiedquire
=> docs(readme): add info about checksum files

site/layouts/partials/footer.amber
The spacing on the footer of dists.ipfs.io seems off. I think the template is eating some double spaces, and does not add spaces for line breaks. Should slightly improve readability/accessibility.
> © IPFS Community | Except as[noted](), content licensed[CC-BY 3.0]() | Source on[Github]()
Screenshot:
=> Tweak footer template to correctly space around links

.gitignore, build-go.sh
This way _all_ the paths are consistent in the compiled binary. I.e., we can finally use plugins.
=> build using go modules

package-lock.json, package.json, site/assets/js/platform.js, site/config.toml, site/layouts/_default/single.amber
This renames all visible mentions of "darwin" to "macOS". But the internal data structures and links still use darwin, to avoid breaking anything.
Closes #235
=> rename darwin to macOS

build-go.sh, deps-check.sh, dist.sh, package-lock.json, package.json
Apparently, export/local on the same line as shell substitution hides any errors from the shell substitution.
Also, lots of quotes.
=> fix: fix shellecheck issues

build-go.sh
The shell linter thing must have broken this.
=> Fix: set goos and goarch correctly

dists/fs-repo-migrations/build_matrix, dists/go-ipfs/build_matrix, site/config.toml
1. Build go-ipfs 0.5.0 and 0.5.1 on openbsd (and linux arm64).
2. Importantly, build the latest migrations on openbsd so upgrading openbsd machines doesn't fail.
HASH: QmXuKUDChMXkcq36CbaggvY3UaAtgpi7yyoAiNy5VD9Dfr
fixes #100
=> feat: build on openbsd

build-go.sh
This will effect future builds. While everything should be fine please be careful to run `ipfs object diff /ipns/dist.ipfs.io /ipfs/HASH` to ensure you haven't replaced any old binaries.
@hsanjuan @Stebalien @jessicaschilling
=> feat: switch to building using -trimpath instead of using the asm and gc trimpath flags

site/assets/less/base.less, site/layouts/_default/single.html
ui tweak to avoid breaking the distribution name in the download button
| before | after |
|--------|------|
| <img width="1328" alt="Screenshot 2020-10-23 at 19 59 21" src="https://user-images.githubusercontent.com/58871/97043404-531c1c80-156a-11eb-9c8a-9fe2cbc6c884.png"> | <img width="1328" alt="Screenshot 2020-10-23 at 19 59 12" src="https://user-images.githubusercontent.com/58871/97043481-76df6280-156a-11eb-9626-61647e13f0ed.png">
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> fix: avoid wrapping app name in dowload btn

dists/fs-repo-migrations/build_matrix, dists/go-ipfs/build_matrix, dists/gx-go/build_matrix, dists/gx/build_matrix, dists/ipfs-cluster-ctl/build_matrix, dists/ipfs-cluster-follow/build_matrix, dists/ipfs-cluster-service/build_matrix, dists/ipfs-ds-convert/build_matrix, dists/ipfs-pack/build_matrix, dists/ipfs-see-all/build_matrix, dists/ipfs-update/build_matrix, dists/ipget/build_matrix
Darwin 386 is not supported by Go 1.15+ (https://github.com/golang/go/issues/34749) so it should be removed from the build matrix of the binaries.
=> remove darwin 386 support as it is not supported by Go 1.15+

build-go.sh, deps-check.sh
On linux, sha512sum is a part of the "coreutils" package. shasum is a part of perl.
=> remove perl dependency

.github/workflows/main.yml, scripts/ci/setup-ipfs.sh
Addressing https://github.com/ipfs/distributions/issues/372.
=> Update dnslink for dist.ipfs.io on merge to master

.github/workflows/main.yml, .github/workflows/nightly.yml, scripts/ci/pin-to-cluster.sh, scripts/ci/setup-ipfs.sh
This PR aims to fix nightly builds: bumps binaries used for build and restores use of bootstrappers, so there is a fallback in case cluster is down or in a weird state.
(CI is green, failures are from previous runs)
=> fix(ci): more robust cluster connect

Dockerfile
Some simple binaries (e.g. that don't use the "net" package) are
statically linked by the Go compiler, so don't have symbol tables,
which caused glibc-check to barf and the build to fail. This updates
glibc-check to a newer version that won't fail if there is no symbol table.
=> fix: don't fail glibc check for statically linked binaries

.github/actions/setup-ipfs/action.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
This PR stabilizes nightly builds:
- makes preconnect to cluster peers async and best-effort (solving **Problem 1**)
- bumps timeout to 30m as downloading binaries from dist.ipfs.io may take  longer when under load. (solving **Problem 2**)
Our nightlies timeout now and then because connecting to one of the cluster peers takes a long time, and that blocks and timeouts an entire build. 
For example: 
- https://github.com/ipfs/distributions/runs/5001510377?check_suite_focus=true#step:3:439 
We don't need to connect to all of them, and not all DNSAddr TXT records need to be valid.
Secondly, `setup-ipfs` stage sometimes fails because it can't fetch go-ipfs binary from dist.ipfs.io (and there is a timeout of 5m around that):
- https://github.com/ipfs/distributions/runs/5026194679?check_suite_foc …
=> fix(ci): stabilize setup-ipfs step

.github/workflows/nightly.yml
Problem – https://github.com/ipfs/distributions/issues/531 got fixed, but the "Problem with" message on commit remains: 
>  ![2021-12-15_22-12](https://user-images.githubusercontent.com/157609/146265676-108a6401-ac0a-4a23-99f9-72505da08ded.png)
=> fix: update nightly status on commits

.github/workflows/main.yml
This PR should fix macOS signing with mitchellh/gon by applying a workaround for https://github.com/mitchellh/gon/issues/56
=> fix: brew tap mitchellh/gon

.github/workflows/nightly.yml, Makefile, ignored-during-nightly
- Tag the ipdx team when the nightly build fails,
- Skip nightly build for legacy code, use the `ignored-during-nightly` list of files,
- Use go version 1.17 for build, that should fix the current failure with quic-go
=> feat: update nightly & signal the ipdx team on failure

.github/workflows/main.yml, .github/workflows/nightly.yml, .tool-versions, dists/go-ipfs/description, package-lock.json, site/config.toml, site/layouts/_default/single.html
This PR extracts cosmetic presentation changes from https://github.com/ipfs/distributions/pull/717
and only adds "kubo" to the HTML of dist.ipfs.io website,  
does not change build pipeline, it still uses go-ipfs.
Can be merged without any risk before #717 
cc @aschmahmann as we discussed this during kubo sync today
=> feat: cosmetic reame to kubo

site/layouts/_default/single.html
Right now there is no link on the website to find package with legacy go-ipfs releases.
I propose we just link to both new and old release lists:
>  ![2022-07-08_16-50](https://user-images.githubusercontent.com/157609/178017962-5fed7609-7447-4425-8856-540cb5f556a5.png)
Closes #738
=> fix: link to legacy go-ipfs releases

.github/workflows/nightly.yml, ignored-during-nightly
The file was used only in Makefiles, but the CI still created a job for
each dist, which was wasteful and noisy:
| Before | After |
| ---- | ---- |
| ![2022-07-08_15-34](https://user-images.githubusercontent.com/157609/178002371-35b19302-7e3c-4901-bf82-fdfa11afd74c.png) |  ![2022-07-08_15-31](https://user-images.githubusercontent.com/157609/178002004-21a79601-57bf-45d4-a55f-89bb43ab451e.png) |
Closes #739
=> fix: respect ignored-during-nightly

README.md
I believe this reflect reality better. cc @Jorropo  to confirm based on 0.14.0
=> docs(readme): clarify that DNSLink

.github/workflows/main.yml
> Part of https://github.com/protocol/infra/issues/910 and https://github.com/protocol/bifrost-infra/issues/2018 
This PR is extracted from #746 to start publishing under new name without changing anything else.
Dual publishing allows us to evaluate a new name without impacting the old one.
Safe to merge, as it does not change anything yet (the full move will happen in #746).
=> feat: dual publish to  /ipns/dist.ipfs.tech

.github/workflows/main.yml, .github/workflows/nightly.yml, Dockerfile, README.md, build-go.sh, dockerized, package-lock.json, package.json, scripts/diff.js, scripts/dist.js, scripts/patch.js, site/assets/js/index.js, site/config.toml, site/layouts/_default/index.xml, site/layouts/_default/single.html, site/layouts/partials/about.md, site/layouts/partials/header.html
> Part of https://github.com/protocol/bifrost-infra/issues/2018 and https://github.com/protocol/infra/issues/910 
This needs https://github.com/protocol/bifrost-infra/pull/2043 (will re-run CI when we have TLS cert set up)
=> refactor: move to dist.ipfs.tech

.tool-versions
I can't release cluster otherwise.
=> Use go1.19 in the build pipeline

build-go.sh
The CI skipped it and didn't actually run that code and it was broken with green ci, this is correct, this time.
=> fix: add support for GOAMD64

dists/ipfs-cluster-follow/build_matrix, dists/ipfs-cluster-service/build_matrix
They are broken since the introduction of Pebble.
We can revert this in the future if we add build flags for it etc.
=> Disable ipfs-cluster 32-bit builds.

dists/fs-repo-migrations/build_matrix, dists/kubo/build_matrix, templates/build_matrix
This is closes https://github.com/ipfs/kubo/issues/9365  by adding ARM64 build target for Windows.
We already provide one for Apple M1 (`darwin arm64`), and
need this for Brave (https://github.com/brave/brave-core-crx-packager/issues/503, cc @mihaiplesa).
=> feat: kubo builds for arm64

.github/workflows/main.yml
The goal is to make it faster, this PR aims to test if using self-hosted runner speeds up release build.
If it is ok, we can decide to set CI_BUILD_RUNS_ON on this repo instead.
cc @galargh  for sanity check +  if we need to safelist this repo somewhere for this to work (i tried to set `CI_BUILD_RUNS_ON` but https://github.com/ipfs/distributions/actions/runs/5799417224/job/15719370344 was stuck waiting for free runner and i cancelled it).
=> feat(ci): use self-hosted runner for faster main build

.github/workflows/main.yml, .github/workflows/nightly.yml
Making sure we run latest versions in preparation for a fix for:
https://github.com/ipfs/distributions/actions/runs/6239183113/job/16944292013#step:6:543
=> chore: update kubo and ipfs-cluster-ctl

.github/actions/setup-ipfs/action.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, package-lock.json, scripts/patch.js
This closes #1053  by switching from old JS tool to newly fixed  (https://github.com/ipfs-shipyard/dnslink-dnsimple/pull/21) GO one (kudos to @ns4plabs).
We will no longer update `.io` version, as it will be CNAMEd to `_dnslink.dist.ipfs.tech` instead.
=> fix: switch to new dnslink updater

.github/workflows/main.yml, .github/workflows/nightly.yml, build-go.sh
Aims to Close https://github.com/ipfs/distributions/issues/673
The meta reason is the entire build pipeline not being written with `set -e`, which means every potential error path needs to be manually handled, or it will be ignored.
For fix here, I suspect things worked fine until we added `glibc-check` here, which made `go build` no longer be the last command in `goBuild`, and if `go build` fails its code is not the code returned by `goBuild`, but we continue to the next command, which may run ok due to no binaries to check :upside_down_face:
=> fix: correct go build error passing

.tool-versions
https://github.com/golang/go/issues?q=milestone%3AGo1.22.6+label%3ACherryPickApproved
part of https://github.com/ipfs/kubo/issues/10436
(1.23 is not ready yet: https://github.com/ipfs/kubo/pull/10486)
=> chore: golang 1.22.6

.tool-versions
Unsafe to use 1.23 until https://github.com/ipfs/kubo/issues/10501 is resolved
=> fix: switch back to go1.22

.github/workflows/main.yml, scripts/ci/sign-new-macos-releases.sh
See https://github.com/ipfs/kubo/issues/9323.
This is a darwin release thing because the signature process for macOS means that we recalculate sha512 and cid and we do this using an absolute path so the result includes the path to the file.
The fix is to cd to the folder and do it from there.
=> fix: do not include full path to binary in .sha512 files

.tool-versions
https://github.com/golang/go/issues?q=milestone%3AGo1.23.4+label%3ACherryPickApproved
=> chore: go v1.23.4

site/layouts/_default/single.html
add link to https://hub.docker.com/r/ipfs/kubo/ in the kubo section of dist.ipfs.tech
fixes #780
=> feat: add docker images link for kubo
